version: '3.4'
# Создание сертификатов самоподписных (вообще лучше пароль и путь в UserSecrets указывать):
# dotnet --info
# dotnet dev-certs https --trust
# dotnet dev-certs https -ep $env:APPDATA\ASP.NET\Https\CPK-api.pfx -p 1234Qwert
# dotnet dev-certs https -ep $env:APPDATA\ASP.NET\Https\CPK-spa-blazor.pfx -p 1234Qwert
# dotnet dev-certs https -ep $env:APPDATA\ASP.NET\Https\CPK-sso.pfx -p 1234Qwert
# Get-ChildItem  -Recurse .\| Where-Object { $_.PSIsContainer }| Where-Object {$_.Name -match "^(bin|obj)$" }| Where-Object {$_.FullName -notmatch ".+node_modules.+"}| Remove-Item -Force -Recurse
# find ./ -regex "^(?!.+\/node_modules\/.*)((.+\/bin\/.*)|(.+\/obj\/.*))$" -type d -exec rm -rf {} \;
services:  
  cpk.sso:
    image: alrosait/CPK-sso:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234Qwert
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/CPK-sso.pfx
      - ApiSwaggerClient=http://localhost:7001
      - SpaBlazorClient=http://localhost:7003 
      - ConnectionString=Host=rc1c-un5wuadesgzjjl01.mdb.yandexcloud.net;Port=6432;SSLMode=Require;TrustServerCertificate=true;Database=cpk2-sso-dev;Username=cpk2-dev;Password=developer$pass
    ports:
      - "7000:80"
      - "8000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  cpk.api:
    image: alrosait/CPK-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - IdentityUrlExternal=https://localhost:8000
      - Authority=http://cpk.sso
      - ConnectionString=Host=rc1c-un5wuadesgzjjl01.mdb.yandexcloud.net;Port=6432;SSLMode=Require;TrustServerCertificate=true;Database=cpk2-dev;Username=cpk2-dev;Password=developer$pass
    ports:
      - "7001:80"

  cpk.spa.server:
    image: alrosait/CPK-spa:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - SsoUri=https://localhost:8000
      - ApiUri=http://localhost:7001
    ports:
     - "7003:80"

  redisdata:
    image: redis:latest
    ports:
      - "6379:6379"
      - "32768:32768"
    volumes: 
      - cpk-redis:/data

volumes:
  cpk-redis:
      external: false